package idl;

/**
* idl/AHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public final class AHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.A value = null;

  public AHolder ()
  {
  }

  public AHolder (idl.A initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.AHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.AHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.AHelper.type ();
  }

}
