package idl;


/**
* idl/AnnuaireOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public interface AnnuaireOperations 
{
  boolean findJob ();
} // interface AnnuaireOperations
