package idl;


/**
* idl/AnnuairePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public class AnnuairePOATie extends AnnuairePOA
{

  // Constructors

  public AnnuairePOATie ( idl.AnnuaireOperations delegate ) {
      this._impl = delegate;
  }
  public AnnuairePOATie ( idl.AnnuaireOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public idl.AnnuaireOperations _delegate() {
      return this._impl;
  }
  public void _delegate (idl.AnnuaireOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean findJob ()
  {
    return _impl.findJob();
  } // findJob

  private idl.AnnuaireOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AnnuairePOATie
