package idl;


/**
* idl/APOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public abstract class APOA extends org.omg.PortableServer.Servant
 implements idl.AOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("testReturn", new java.lang.Integer (0));
    _methods.put ("testNoReturn", new java.lang.Integer (1));
    _methods.put ("testEasy", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // idl/A/testReturn
       {
         org.omg.CORBA.Any parametre = in.read_any ();
         String $result = null;
         $result = this.testReturn (parametre);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // idl/A/testNoReturn
       {
         org.omg.CORBA.Any parametre = in.read_any ();
         this.testNoReturn (parametre);
         out = $rh.createReply();
         break;
       }

       case 2:  // idl/A/testEasy
       {
         this.testEasy ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/A:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public A _this() 
  {
    return AHelper.narrow(
    super._this_object());
  }

  public A _this(org.omg.CORBA.ORB orb) 
  {
    return AHelper.narrow(
    super._this_object(orb));
  }


} // class APOA
