package idl;


/**
* idl/BPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public class BPOATie extends BPOA
{

  // Constructors

  public BPOATie ( idl.BOperations delegate ) {
      this._impl = delegate;
  }
  public BPOATie ( idl.BOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public idl.BOperations _delegate() {
      return this._impl;
  }
  public void _delegate (idl.BOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String testReturn (org.omg.CORBA.Any parametre)
  {
    return _impl.testReturn(parametre);
  } // testReturn

  public void testNoReturn (org.omg.CORBA.Any parametre)
  {
    _impl.testNoReturn(parametre);
  } // testNoReturn

  public void testEasy ()
  {
    _impl.testEasy();
  } // testEasy

  private idl.BOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class BPOATie
