package idl;


/**
* idl/ClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public abstract class ClientPOA extends org.omg.PortableServer.Servant
 implements idl.ClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("returnOfJob", new java.lang.Integer (0));
    _methods.put ("initOrdonnaceur", new java.lang.Integer (1));
    _methods.put ("createAndExecuteJob", new java.lang.Integer (2));
    _methods.put ("printReturn", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // idl/Client/returnOfJob
       {
         org.omg.CORBA.Any reponse = in.read_any ();
         this.returnOfJob (reponse);
         out = $rh.createReply();
         break;
       }

       case 1:  // idl/Client/initOrdonnaceur
       {
         this.initOrdonnaceur ();
         out = $rh.createReply();
         break;
       }

       case 2:  // idl/Client/createAndExecuteJob
       {
         String nameRef = in.read_string ();
         String interfaceName = in.read_string ();
         String methodeName = in.read_string ();
         org.omg.CORBA.Any parametre = in.read_any ();
         this.createAndExecuteJob (nameRef, interfaceName, methodeName, parametre);
         out = $rh.createReply();
         break;
       }

       case 3:  // idl/Client/printReturn
       {
         this.printReturn ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/Client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Client _this() 
  {
    return ClientHelper.narrow(
    super._this_object());
  }

  public Client _this(org.omg.CORBA.ORB orb) 
  {
    return ClientHelper.narrow(
    super._this_object(orb));
  }


} // class ClientPOA
