package idl;


/**
* idl/COperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public interface COperations 
{
  String testReturn (org.omg.CORBA.Any parametre);
  void testNoReturn (org.omg.CORBA.Any parametre);
  void testEasy ();
} // interface COperations
