package idl;

/**
* idl/OrdonnanceurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public final class OrdonnanceurHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.Ordonnanceur value = null;

  public OrdonnanceurHolder ()
  {
  }

  public OrdonnanceurHolder (idl.Ordonnanceur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.OrdonnanceurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.OrdonnanceurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.OrdonnanceurHelper.type ();
  }

}
