package idl;


/**
* idl/OrdonnanceurPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public class OrdonnanceurPOATie extends OrdonnanceurPOA
{

  // Constructors

  public OrdonnanceurPOATie ( idl.OrdonnanceurOperations delegate ) {
      this._impl = delegate;
  }
  public OrdonnanceurPOATie ( idl.OrdonnanceurOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public idl.OrdonnanceurOperations _delegate() {
      return this._impl;
  }
  public void _delegate (idl.OrdonnanceurOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void execute (idl.Job j)
  {
    _impl.execute(j);
  } // execute

  public void createThreadExecutor ()
  {
    _impl.createThreadExecutor();
  } // createThreadExecutor

  private idl.OrdonnanceurOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class OrdonnanceurPOATie
