package idl;


/**
* idl/ServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public interface ServeurOperations 
{
  boolean isReady ();
  void doTheJob (idl.Job j);
  void returnOfJobToTheClient ();
} // interface ServeurOperations
