package idl;


/**
* idl/ServeurPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* vendredi 23 mars 2018 15 h 31 CET
*/

public class ServeurPOATie extends ServeurPOA
{

  // Constructors

  public ServeurPOATie ( idl.ServeurOperations delegate ) {
      this._impl = delegate;
  }
  public ServeurPOATie ( idl.ServeurOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public idl.ServeurOperations _delegate() {
      return this._impl;
  }
  public void _delegate (idl.ServeurOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean isReady ()
  {
    return _impl.isReady();
  } // isReady

  public void doTheJob (idl.Job j)
  {
    _impl.doTheJob(j);
  } // doTheJob

  public void returnOfJobToTheClient ()
  {
    _impl.returnOfJobToTheClient();
  } // returnOfJobToTheClient

  private idl.ServeurOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ServeurPOATie
