
/**
* AHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ordonnanceur.idl
* Thursday, March 29, 2018 at 3:40:28 PM Central European Summer Time
*/

abstract public class AHelper
{
  private static String  _id = "IDL:A:1.0";

  public static void insert (org.omg.CORBA.Any a, A that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static A extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AHelper.id (), "A");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static A read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, A value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static A narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof A)
      return (A)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AStub stub = new _AStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static A unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof A)
      return (A)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AStub stub = new _AStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
