
/**
* AOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ordonnanceur.idl
* Thursday, March 29, 2018 at 3:40:28 PM Central European Summer Time
*/

public interface AOperations 
{
  void a1 (org.omg.CORBA.Any params, String serverRef, String objectName);
  void a2 (org.omg.CORBA.Any params, String serverRef, String objectName);
} // interface AOperations
