
/**
* SchedulerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ordonnanceur.idl
* Thursday, March 29, 2018 at 3:40:28 PM Central European Summer Time
*/

public abstract class SchedulerPOA extends org.omg.PortableServer.Servant
 implements SchedulerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("task", new java.lang.Integer (0));
    _methods.put ("callback", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Scheduler/task
       {
         TaskParam param = TaskParamHelper.read (in);
         this.task (param);
         out = $rh.createReply();
         break;
       }

       case 1:  // Scheduler/callback
       {
         String objectName = in.read_string ();
         this.callback (objectName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Scheduler:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Scheduler _this() 
  {
    return SchedulerHelper.narrow(
    super._this_object());
  }

  public Scheduler _this(org.omg.CORBA.ORB orb) 
  {
    return SchedulerHelper.narrow(
    super._this_object(orb));
  }


} // class SchedulerPOA
