
/**
* SchedulerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ordonnanceur.idl
* Thursday, March 29, 2018 at 3:40:28 PM Central European Summer Time
*/

public interface SchedulerOperations 
{
  void task (TaskParam param);
  void callback (String objectName);
} // interface SchedulerOperations
