
/**
* TaskParam.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ordonnanceur.idl
* Thursday, March 29, 2018 at 3:40:28 PM Central European Summer Time
*/

public final class TaskParam implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String objectName = null;
  public String interfaceName = null;
  public String methodName = null;
  public String clientRef = null;
  public org.omg.CORBA.Any params = null;

  public TaskParam ()
  {
  } // ctor

  public TaskParam (int _id, String _objectName, String _interfaceName, String _methodName, String _clientRef, org.omg.CORBA.Any _params)
  {
    id = _id;
    objectName = _objectName;
    interfaceName = _interfaceName;
    methodName = _methodName;
    clientRef = _clientRef;
    params = _params;
  } // ctor

} // class TaskParam
