package idl;


/**
* idl/AOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface AOperations 
{
  String testReturn ();
  void testNoReturn (org.omg.CORBA.Any parametre);
  void testEasy ();
} // interface AOperations
