package idl;


/**
* idl/C.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface C extends COperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface C
