package idl;


/**
* idl/ClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public abstract class ClientPOA extends org.omg.PortableServer.Servant
 implements idl.ClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callBack", new java.lang.Integer (0));
    _methods.put ("toString", new java.lang.Integer (1));
    _methods.put ("findRetour", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // idl/Client/callBack
       {
         int idJob = in.read_long ();
         org.omg.CORBA.Any retour = in.read_any ();
         this.callBack (idJob, retour);
         out = $rh.createReply();
         break;
       }

       case 1:  // idl/Client/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // idl/Client/findRetour
       {
         int idJob = in.read_long ();
         this.findRetour (idJob);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:idl/Client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Client _this() 
  {
    return ClientHelper.narrow(
    super._this_object());
  }

  public Client _this(org.omg.CORBA.ORB orb) 
  {
    return ClientHelper.narrow(
    super._this_object(orb));
  }


} // class ClientPOA
