package idl;


/**
* idl/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface ClientOperations 
{
  void callBack (int idJob, org.omg.CORBA.Any retour);
  String _toString ();
  void findRetour (int idJob);
} // interface ClientOperations
