package idl;


/**
* idl/COperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface COperations 
{
  String testReturn (org.omg.CORBA.Any parametre);
  void testNoReturn (org.omg.CORBA.Any parametre);
  void testEasy ();
} // interface COperations
