package idl;

/**
* idl/JobHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public final class JobHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.Job value = null;

  public JobHolder ()
  {
  }

  public JobHolder (idl.Job initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.JobHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.JobHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.JobHelper.type ();
  }

}
