package idl;


/**
* idl/OrdonnanceurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface OrdonnanceurOperations 
{
  void execute (idl.Job j);
  void referenceServeur (String nameReference);
} // interface OrdonnanceurOperations
