package idl;

/**
* idl/ServeurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public final class ServeurHolder implements org.omg.CORBA.portable.Streamable
{
  public idl.Serveur value = null;

  public ServeurHolder ()
  {
  }

  public ServeurHolder (idl.Serveur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = idl.ServeurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    idl.ServeurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return idl.ServeurHelper.type ();
  }

}
