package idl;


/**
* idl/ServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public interface ServeurOperations 
{
  boolean isReady ();
  void execute (idl.Job j);
} // interface ServeurOperations
