package idl;


/**
* idl/ServeurPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ordonnanceur.idl
* lundi 2 avril 2018 20 h 13 CEST
*/

public class ServeurPOATie extends ServeurPOA
{

  // Constructors

  public ServeurPOATie ( idl.ServeurOperations delegate ) {
      this._impl = delegate;
  }
  public ServeurPOATie ( idl.ServeurOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public idl.ServeurOperations _delegate() {
      return this._impl;
  }
  public void _delegate (idl.ServeurOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean isReady ()
  {
    return _impl.isReady();
  } // isReady

  public void execute (idl.Job j)
  {
    _impl.execute(j);
  } // execute

  private idl.ServeurOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ServeurPOATie
